name: Android CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write
  contents: read

env:
  main_project_module: app
  library_module: library

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK Release - ${{ env.main_project_module }}
        run: ./gradlew ${{ env.main_project_module }}:assembleRelease

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: APK Release
          path: ${{ env.main_project_module }}/build/outputs/apk/release/*.apk

  build-aar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build AAR Release - ${{ env.library_module }}
        run: ./gradlew ${{ env.library_module }}:assembleRelease

      - name: Upload AAR Release
        uses: actions/upload-artifact@v4
        with:
          name: AAR Release
          path: ${{ env.library_module }}/build/outputs/aar/*.aar
