name: Build Android AAR

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-aar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build AAR
        run: ./gradlew :library:assembleRelease
        # ajuste ":library:" para o nome do módulo do seu projeto

      - name: Upload AAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-aar
          path: library/build/outputs/aar/*.aar
